const {chromium}=require('playwright'); const seed=require('./seed.js');
(async()=>{ const b=await chromium.launch(); const errs=[], bad=[]; const ok=(c,m)=>{ if(!c) bad.push(m); else console.log('ok ',m); };
const p=await (await b.newContext({viewport:{width:390,height:844}})).newPage(); p.on('pageerror',e=>errs.push(e.message));
await p.goto('http://127.0.0.1:8765/prev216.html'); await p.waitForTimeout(400); await seed(p); await p.waitForTimeout(1200);
const E=(f,a)=>p.evaluate(f,a), W8=ms=>p.waitForTimeout(ms);
await E(()=>{ CELON=true; CELQ.length=0; ['lp','swipe','scrub','mini2'].forEach(k=>{ try{ hintDone(k); }catch(e){} }); });
const set=o=>E(o=>{ const h=hoyISO(), w=wdIdx(h); const r=[0,1,2,3,4,5,6].filter(x=>x!==w); CFG.diasFS=o.nodays?[]:[r[0],r[2],r[4]]; CFG.diasBS=o.nodays?[]:[r[1],r[3]]; CFG.prog={}; CFG.mov=Object.assign({on:true,post:true,libre:true,hora:null},o.mov||{});
  for(let i=SESS.length-1;i>=0;i--) if(SESS[i].fecha===h) SESS.splice(i,1); mov=null; draft=null; bike.running=false; (o.mv||[]).forEach((m,i)=>SESS.push({id:'mv'+i,kind:'mov',fecha:h,tipo:'Movilidad de cuerpo entero',min:m,items:Object.keys(MOV).slice(0,5)}));
  SESS.sort((a,b)=>b.fecha.localeCompare(a.fecha)); NAV.length=0; go('home'); },o);
const tap=async sel=>{ await E(s=>document.querySelector(s).click(),sel); await W8(800); };
await set({}); await W8(700); await tap('#app .hero.lb'); ok(await E(()=>view)==='estirar','nada hecho: tocar → Movilidad');
await set({}); await W8(700); await tap('#app .hero.lb [data-mov]'); ok(await E(()=>view==='mov'&&!!mov),'Empezar → arranca movilidad'); await E(()=>{ mov=null; });
await set({mv:[12]}); await W8(700); await tap('#app .hero.lb'); ok(await E(()=>view==='dia'&&histEx==='mv0'),'hecha: tocar → detalle');
await set({mv:[12,8]}); await W8(700); await tap('#app .hero.lb'); ok(await E(()=>!!document.querySelector('.pop, .sheet:not([hidden])')&&view==='home'),'dos veces: tocar → lista del día'); await E(()=>{ try{ popClose(true); }catch(e){} try{ sheetClose(); }catch(e){} });
await set({nodays:1}); await W8(700); await tap('#app .hero.lb'); ok(await E(()=>view==='ajustes'&&ajSec==='semana'),'sin días → Ajustes › Semana');
await set({mov:{on:false}}); await W8(700); await tap('#app .hero.lb'); ok(await E(()=>view)==='home','apagada: la card no navega');
await set({}); await W8(700); const it=await E(()=>{ const x=lpItems(document.querySelector('#app .hero.lb')); return x.it.map(i=>i.t); }); ok(JSON.stringify(it)==='["Empezar movilidad","Elegir zonas","Fuerza","Cardio suave"]','apretado: '+JSON.stringify(it));
await set({mv:[12,8]}); await W8(700); const it2=await E(()=>lpItems(document.querySelector('#app .hero.lb')).it.map(i=>i.t+'|'+(i.d||''))); ok(it2[0]==='Ver movilidad|20 min','apretado hecha: '+it2[0]);
await set({}); await W8(700); await tap('#app .hero.lb [data-go-b]'); ok(await E(()=>view==='bici'&&bike.running),'Cardio suave → arranca cardio'); await E(()=>{ try{ bikeDiscard(); }catch(e){} bike.running=false; });
await set({mov:{hora:'noc'}}); await W8(700); ok(await E(()=>!document.querySelector('#app [data-card="mov"]')),'horario propio: una sola card');
console.log(bad.length?'FALLAS:\n'+bad.join('\n'):'TODO OK','\nERRS',JSON.stringify(errs.slice(0,5))); await b.close(); })();
